export const DefaultCodes = () =>{
    return {
        base : {
            "width":"",
            "height":"",
            "cursor": "",
            "color" : "black;",
            "background-color":"white;",
            "font-size": "16px;",
            "margin": "10px;",
            "padding": "10px;",
            "border": "1px solid black;",
            "border-radius": "",
            "border-bottom-left-radius": "",
            "border-bottom-right-radius": "",
            "border-top-left-radius": "",
            "border-top-right-radius": "",
            "border-left": "",
            "border-top": "",
            "border-right": "",
            "border-bottom": "",
            "box-shadow": "",
            "letter-spacing": "",
            "-webkit-text-stroke":"",
            "text-decoration": "",
            "font-style":"",
            "font-weight":"",
            "background":"",
            "filter":"",
            "transition":"",
            "content": "",
            "outline":"",
            "accent-color":""
        },
        hover : {
            "width":"",
            "height":"",
            "color" : "",
            "background-color":"",
            "font-size": "",
            "margin": "",
            "padding": "",
            "border": "",
            "border-radius": "",
            "border-bottom-left-radius": "",
            "border-bottom-right-radius": "",
            "border-top-left-radius": "",
            "border-top-right-radius": "",
            "border-left": "",
            "border-top": "",
            "border-right": "",
            "border-bottom": "",
            "box-shadow": "",
            "letter-spacing": "",
            "-webkit-text-stroke":"",
            "text-decoration": "",
            "font-style":"",
            "font-weight":"",
            "background":"",
            "filter":"",
            "transition":"",
            "content": "",
            "outline":"",
            "accent-color":""
        }
    }
}